### ISSUE TITLE
gitbook生成的PDF文件的Index中文有乱码

### ISSUE THREAD

**Issue by lazyparser** [tinyclub/open-shell-book#1]
参照目前 README.md 生成的PDF文件， 从布尔运算开始到用户管理部分的Index有乱码。

![open-shell-book-issue-index](https://cloud.githubusercontent.com/assets/1802104/19958727/78576bf4-a1dc-11e6-9eab-5554d3a6d988.png)

**Comment by lazyparser** [comment]
Ubuntu 14.04 系统， 参照README.md生成的PDF。
下载了gitbook上的PDF版本， Index是正常的， 可能是build的环境不一致导致的。

**Comment by lzufalcon** [comment]
确实是，这部分可以对照 https://github.com/tinyclub/cloud-lab 的环境确认是是否还存在。

**Comment by suifeng1314** [comment]
在open-shell-book文件里面还要只想一下book.json安装所需插件  gitbook install ./

**Comment by lazyparser** [comment]
close outdated issue.
